# What is NumPy?
- NumPy is a Python library used for working with arrays.

- It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very #easy.

In [1]:
# importing numpy 
import numpy as np

In [5]:
# create a basic numpy array from list 
var=np.array([1,2,3,4,5])
print(var)
type(var)

[1 2 3 4 5]


numpy.ndarray

In [6]:
# create a basic numpy array from tuple 
var=np.array((1,2,3,4,5))
print(var)
type(var)

[1 2 3 4 5]


numpy.ndarray

In [13]:
# Dimension of arrays
# 0-d array
arr0 = np.array(10)
print(arr0)

# 1-d array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

#2-d array 
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

#3-d array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

10
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
# number of dimension in array 
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


0
1
2
3


In [22]:
# indexing the array 
print(arr3[0][1][2])
print(arr3[0][1][-1]) # can also be indexed using negative value 

6
6


In [26]:
# slicing the array 
print(arr3[0][1][2])
print(arr3[0,1,2]) # second method of slicing
print(arr3[0][1][:2]) # can also be indexed using negative value 

6
6
[4 5]


In [25]:
# slining array skipping 1 value 
print(arr1)
print(arr1[1:5:2])

[1 2 3 4 5]
[2 4]


In [34]:
# Shapes of array
print(arr0)
print(arr0.shape)
print(arr1)
print(arr1.shape)
print(arr2)
print(arr2.shape)
print(arr3)
print(arr3.shape)

10
()
[1 2 3 4 5]
(5,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
